- public/views/shortcode_template.php
https://app.asana.com/0/1202669984981490/1204094144322035/f
> Show Only Image If Feed Detected

- public/assets/js/public.js
https://app.asana.com/0/1201828192748892/1204350740909324/f
Note this is the PR for DA free. The PR for DA Pro is here: https://github.com/nsquared-team/draw-attention-pro/pull/16 Please be sure to test both
> Apply ugly hacky fix for Elementor popup duplicating DA images

- .github/config/changelog_configuration.json
- .github/workflows/release.yml
https://app.asana.com/0/1202852195727075/1204553643631715/f
Minor fixes to the ci/release workflow
> Fix "Set Tag Name for Release" and Slack notifications on Draw Attention

- .github/workflows/release.yml
https://app.asana.com/0/1202852195727075/1204553643631715/f
Fixing CI release workflow to send dev changelog to slack
> remove all special characters from JSON payload keeping only newline characters

- .github/workflows/release.yml
- README.md
-
This corrects the file where we're appending the link to additional changelog information: `README.md --> readme.txt`
> append the more infor changelog url to the readme.txt file

- public/includes/lib/drag-drop-featured-image/assets/scripts/drag-drop-uploader.js
- public/includes/lib/drag-drop-featured-image/index.php
https://app.asana.com/0/1202852195727075/1204622680567030/f
Following [this HS ticket](https://secure.helpscout.net/conversation/2245820840/167580#thread-6700463277) where a vulnerability in DA `ajax_set_featured_image` function was reported, this PR attempts to solve the issue described and checks for user capability before allowing the request to go through
> Security - nonce verification and capability check for editing featured image

- readme.txt
> Update tested up to

- admin/class-drawattention-admin.php
- public/class-drawattention.php
- public/includes/lib/drag-drop-featured-image/index.php
https://app.asana.com/0/1202669984981490/1205163732429935/f
> Fix php deprecation warnings

- .github/workflows/deploy.yml
- .github/workflows/release.yml
- Gruntfile.js
- external/actions-scripts/format-changelog.php
https://app.asana.com/0/1202852195727075/1205759649138677/f
Fix deploy workflow
> Fix deploy workflow

- readme.txt
https://app.asana.com/0/1202131669252825/1205432810978451/f
> Tested up to WP 6.4

- public/includes/lib/drag-drop-featured-image/index.php
https://app.asana.com/0/1202852195727075/1205698675766412/f
Sync to DA Free from DA PRO - Resolve Conflict with Conditional Featured Image Plugin
> Sync to DA Free from DA PRO - Resolve Conflict with Conditional Featured Image Plugin

- .github/workflows/release.yml
https://app.asana.com/0/1202852195727075/1205702351861191/f
Draw Attention Free weekly releases (Tuesday)
> Draw Attention Free weekly releases (Tuesday)

- public/class-drawattention.php
https://app.asana.com/0/1202852195727075/1206341411266776/f
Fix include_once paths
> Fix include_once paths

- readme.txt
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206376822242083
> Update readme.txt WordPress 6.5

- public/includes/da-newsletter.php
- public/includes/lib/CMB2/includes/CMB2_Base.php
https://app.asana.com/0/1202993069895285/1206964836665702/f
> Fixed Newsletter component showing up on different screens.

- public/assets/css/custom-meta-box-styles.css
Task: https://app.asana.com/0/1205781917284155/1206694296827299/f
> Hid the move to trash button.

- admin/assets/css/draw-attention-block.css
- admin/assets/js/draw-attention-block.js
Task: https://app.asana.com/0/1205781917284155/1207117130718333/f
> Widget live preview

- .github/workflows/ci.yml
- public/assets/css/custom-meta-box-styles.css
https://app.asana.com/0/1202852195727075/1207326329278641/f
Scope DA styles to just the DA modal
> Scope DA styles to just the DA modal

- readme.txt
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207069093181666
> Update readme.txt WordPress 6.6

- public/assets/css/custom-meta-box-styles.css
https://app.asana.com/0/1202852195727075/1208321613617541/f
Only hide the trash link on da-image post types
> Only hide the trash link on da-image post types

- public/views/shortcode_template.php
Asana: https://app.asana.com/0/1202852195727079/1203452778207394/f
> Improve active spot focus state

- draw-attention.php
https://app.asana.com/0/1202993069895285/1209704975216620/f
Ticket: Conflict with WP MapIt not displaying drawing tools
> Fix Conflict with WP MapIt not displaying drawing tools

- public/includes/da-newsletter.php
https://app.asana.com/0/1203769543421418/1209673586295507/f
Hide DA Newsletter subscription - causing issues for users who want to sign up
> Hide DA Newsletter subscription - causing issues for users who want to sign up 

- public/assets/js/public.js
- public/includes/lib/drag-drop-featured-image/index.php
Asana: https://app.asana.com/1/1992899177764/project/1203769543421418/task/1209979380059674?focus=true
REF PR on the PRO version:
https://github.com/nsquared-team/draw-attention-pro/pull/47
> Prevent duplicate tooltip activation and ensure visibility of hotspots

- public/includes/lib/drag-drop-featured-image/index.php
- readme.txt
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208995103591334
> Update README.md WordPress 6.8

- .github/workflows/maintenance.yaml
Asana task : https://app.asana.com/1/1992899177764/project/1206733695124384/task/1210531583627961?focus=true
Description : Updated merge conflict label to v3
> Updating merge conflict label to v3

- .github/workflows/ci.yml
- .prettierignore
- admin/assets/js/leaflet.draw.js
- public/assets/js/public.js
https://app.asana.com/1/1992899177764/project/1203769543421418/task/1210723189262132?focus=true
Support Visibility Detection for DA Hotspots Within Dynamic UI Containers
> Support Visibility Detection for DA Hotspots Within Dynamic UI Containers

- public/assets/css/custom-meta-box-styles.css
- public/assets/js/news-letter.js
- public/includes/da-newsletter.php
Set up DA newsletter form in the plugin again
https://app.asana.com/1/1992899177764/project/1203769543421418/task/1210616837477450?focus=true
> Setup mailerlite newsletter with our mini plugin
